export const LAY_DANH_SACH_PHIM = 'LAY_DANH_SACH_PHIM'
export const LAY_DANH_SACH_BANNER = 'LAY_DANH_SACH_BANNER'
export const LAY_DANH_SACH_MP_BANNER = 'LAY_DANH_SACH_MP_BANNER'
export const THONG_TIN_PHIM_THEO_ID = 'THONG_TIN_PHIM_THEO_ID'

export const LAY_DANH_SACH_LOGO = 'LAY_DANH_SACH_LOGO'
export const LAY_THONG_TIN_THEO_HE_THONG_RAP = 'LAY_THONG_TIN_THEO_HE_THONG_RAP'

export const LAY_THONG_LICH_CHIEU_THEO_HE_THONG_RAP =
  'LAY_THONG_LICH_CHIEU_THEO_HE_THONG_RAP'

export const GET_SEARCH_MOIVE = 'GET_SEARCH_MOIVE'

export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'

export const SUCCESS = 'success'
export const WARING = 'warning'
export const ERROR = 'error'
