export const LAY_DANH_SACH_PHIM = 'LAY_DANH_SACH_PHIM'
export const LAY_DANH_SACH_BANNER = 'LAY_DANH_SACH_BANNER'
export const LAY_DANH_SACH_MP_BANNER = 'LAY_DANH_SACH_MP_BANNER'
export const THONG_TIN_PHIM_THEO_ID = 'THONG_TIN_PHIM_THEO_ID'
