export const LAY_DANH_SACH_PHIM = 'LAY_DANH_SACH_PHIM'
export const LAY_DANH_SACH_BANNER = 'LAY_DANH_SACH_BANNER'
export const LAY_DANH_SACH_MP_BANNER = 'LAY_DANH_SACH_MP_BANNER'
export const THONG_TIN_PHIM_THEO_ID = 'THONG_TIN_PHIM_THEO_ID'

export const LAY_DANH_SACH_LOGO = 'LAY_DANH_SACH_LOGO'
export const LAY_THONG_TIN_THEO_HE_THONG_RAP = 'LAY_THONG_TIN_THEO_HE_THONG_RAP'

export const LAY_THONG_LICH_CHIEU_THEO_HE_THONG_RAP =
  'LAY_THONG_LICH_CHIEU_THEO_HE_THONG_RAP'

export const GET_SEARCH_MOIVE = 'GET_SEARCH_MOIVE'

export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'

export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAIL = 'SIGNIN_FAIL'

export const SUCCESS = 'success'
export const WARNING = 'warning'
export const ERROR = 'error'
export const CONFIRM = 'CONFIRM'

export const UPDATE_AUTH = 'UPDATE_AUTH'
export const SET_AUTH = 'SET_AUTH'

export const GET_PARAMS = 'GET_PARAMS'
export const GET_ROOM_CINEMA = 'GET_ROOM_CINEMA'
export const CHOOSEN_SEAT = 'CHOOSEN_SEAT'

export const USER_BOOKING_FAIL = 'USER_BOOKING_FAIL'
export const USER_BOOKING_SUCCESS = 'USER_BOOKING_SUCCESS'
export const REQUITE_CHOOSING_SEAT = 'REQUITE_CHOOSING_SEAT'
export const USER_BOOKING_WARNING = 'USER_BOOKING_WARNING'

export const GET_AUTH = 'GET_AUTH'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_LOGOUT_ALERT = 'USER_LOGOUT_ALERT'
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'

export const GET_PROFILE = 'GET_PROFILE'
